### ISSUE TITLE
Добавить инфу по репозиториям в README

### ISSUE THREAD

**Issue by timofeiryko** [hpmor-game/obsidian-docs#1]
Нужно добавить раздел в README, в котором будут перечислены все актуальные (не пустые) репозитории со ссылками, а также для каждого репо - краткие описания, что это и зачем + информация о состоянии (что-то вроде "стадия: запланировано / начато / в разработке / почти готово / закончено", почти готово - значит, осталось только протестировать и/или исправить минорные баги, закончено - на даннный момент часть закончена)

**Comment by SDesya74** [comment]
Стадии можно описывать в milestones и issues конкретного репозитория, а с остальным согласен

**Comment by timofeiryko** [comment]
В README тоже хорошо бы. Чтобы потенциальные донатеры и просто интересующиеся смотрели бегло на части проекта и такие: крутые ребята, у них уже вот это вот сделано, и чтобы прогресс заметен был "снаружи"
